// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function LoadConfig():Promise<main.LogConfig>;

export function SaveConfig(arg1:main.LogConfig):Promise<string>;

export function StartCollectors():Promise<void>;
